# configs/evaluation/eval_hm_metrics.yaml
metrics: ["loss", "spearmanr_hm", "uuas", "root_acc"]

# The two crucial settings for H&M replication:
punctuation_strategy: "xpos"
filter_by_non_punct_len: false