# configs/embeddings/elmo_l1_ud_ewt_full.yaml
# Uses the SAME HDF5 files as elmo_l2_ud_ewt_full, just selects a different layer.

source_model_name: "elmo_original_5.5B_ud_ewt_full_L1" # Indicate Layer 1
layer_index: 1 # 0-indexed, so ELMo's 2nd layer (output of 1st BiLSTM)
paths:
  train: "data_staging/ud_ewt_official_processed/elmo_hdf5_layers/en_ewt-ud-train.elmo-layers.hdf5"
  dev:   "data_staging/ud_ewt_official_processed/elmo_hdf5_layers/en_ewt-ud-dev.elmo-layers.hdf5"
  test:  "data_staging/ud_ewt_official_processed/elmo_hdf5_layers/en_ewt-ud-test.elmo-layers.hdf5"
dimension: 1024 