name: ud_ewt
preload: true
paths:
  conllu_train: data/ud_english_ewt_official/en_ewt-ud-train.conllu
  conllu_dev:   data/ud_english_ewt_official/en_ewt-ud-dev.conllu
  conllu_test:  data/ud_english_ewt_official/en_ewt-ud-test.conllu 