# configs/dataset/ud_hindi_hdtb.yaml
name: ud_hindi_hdtb
preload: true
paths:
  conllu_train: data/ud_hindi_hdtb/hi_hdtb-ud-train.conllu
  conllu_dev:   data/ud_hindi_hdtb/hi_hdtb-ud-dev.conllu
  conllu_test:  data/ud_hindi_hdtb/hi_hdtb-ud-test.conllu