name: UD_Indonesian-GSD
preload: true
paths:
  conllu_train: data/ud/UD_Indonesian-GSD/train.conllu
  conllu_dev:   data/ud/UD_Indonesian-GSD/dev.conllu
  conllu_test:  data/ud/UD_Indonesian-GSD/test.conllu
