name: UD_Spanish-AnCora
preload: true
paths:
  conllu_train: data/ud/UD_Spanish-AnCora/train.conllu
  conllu_dev:   data/ud/UD_Spanish-AnCora/dev.conllu
  conllu_test:  data/ud/UD_Spanish-AnCora/test.conllu
