# configs/training/adam_modern_scheduler.yaml
# A modern training regimen using the Adam optimizer and a standard ReduceLROnPlateau scheduler.
defaults:
  - adam

lr_scheduler_with_reset:
  enable: false

scheduler:
  enable: true
  name: "ReduceLROnPlateau"
  mode: "min"
  factor: 0.1
  patience: 5

early_stopping_metric: "loss"
early_stopping_delta: 0.0001
patience: 10
batch_size: 20