# configs/training/smoke_test.yaml
# Minimal training parameters for quick smoke testing.
optimizer:
  name: "Adam"
  lr: 0.001
batch_size: 1
epochs: 2
patience: 2
early_stopping_metric: "loss"
early_stopping_delta: 0.001
lr_scheduler_with_reset:
  enable: false
save_every_epoch_checkpoint: true