defaults:
  - job: train_probe
  - dataset: ud_ewt/ud_english_ewt_full
  - embeddings: ud_ewt/elmo/L1
  - model: hf_base
  - probe: distance
  - probe_rank@probe: "128"
  - training: adam
  - evaluation: default
  - runtime: mps
  - logging: wandb
  - experiment: ???      # stub enables experiment=… overrides
  - _self_

experiment_name: ${experiment.name}

hydra:
  run:
    # The output path is now based on the choice from the 'experiment' config group.
    dir: outputs/${experiment_name}
  sweep:
    # The 'hydra.job.name' is the name of the job being run (e.g., train_probe).
    dir: multirun/${hydra.job.name}_${now:%Y-%m-%d_%H-%M-%S}
    # The subdirectory for each individual job within the sweep.
    # This uses the specific experiment name for each job, which IS available
    # at the time the job is launched.
    subdir: ${experiment.name}

  job:
    chdir: true
