# configs/config.yaml
# This is the main configuration file. It only defines the configuration GROUPS.
# The actual choices for each group are delegated to the specific experiment file.

defaults:
  # These lines define the "slots" that MUST be filled by an experiment config.
  # The '???' makes the choice mandatory.
  - job: train_probe
  - dataset: ???
  - embeddings: ???
  - model: hf_base
  - probe: ???
  - probe_rank@probe: ???
  - training: ???
  - evaluation: default
  - runtime: mps
  - logging: wandb
  - experiment: ???      # This is how we select which experiment to run.
  - _self_

# This value is now defined in the experiment config and used here for the output dir.
experiment_name: ${experiment.name}

hydra:
  run:
    dir: outputs/${experiment.name}
  sweep:
    dir: multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${experiment.name}
  job:
    chdir: true