defaults:
  - job: train_probe
  - dataset: ud_ewt/ud_english_ewt_full
  - embeddings: ud_ewt/elmo/L1
  - model: hf_base
  - probe: distance
  - probe_rank@probe: "128"
  - training: adam
  - training/schedule_hm
  - evaluation: default
  - runtime: mps
  - logging: wandb
  - experiment: ???      # stub enables experiment=… overrides
  - _self_

experiment_name: ${experiment.name}

hydra:
  run:
    # The output path is now based on the choice from the 'experiment' config group.
    dir: outputs/${experiment_name}
  sweep:
    dir: multirun/${experiment_name}
    subdir: job_${hydra.job.num}
  job:
    chdir: true
