name: UD_Russian-SynTagRus
preload: true
paths:
  conllu_train: data/ud/UD_Russian-SynTagRus/train.conllu
  conllu_dev:   data/ud/UD_Russian-SynTagRus/dev.conllu
  conllu_test:  data/ud/UD_Russian-SynTagRus/test.conllu
