# configs/embeddings/ud_ewt/elmo/L1.yaml
# ELMo Layer 1 (Bottom BiLSTM) on UD EWT
source_model_name: elmo
layer_index: 1
dimension: 1024
paths:
  train: "data_staging/embeddings/ud_english_ewt_full/elmo/ud_english_ewt_full_train_layers-all_align-mean.hdf5"
  dev:   "data_staging/embeddings/ud_english_ewt_full/elmo/ud_english_ewt_full_dev_layers-all_align-mean.hdf5"
  test:  "data_staging/embeddings/ud_english_ewt_full/elmo/ud_english_ewt_full_test_layers-all_align-mean.hdf5"
