name: UD_Bulgarian-BTB
preload: true
paths:
  conllu_train: data/ud/UD_Bulgarian-BTB/train.conllu
  conllu_dev:   data/ud/UD_Bulgarian-BTB/dev.conllu
  conllu_test:  data/ud/UD_Bulgarian-BTB/test.conllu
