# configs/embeddings/ptb_sd/bert-base-cased/L7.yaml
source_model_name: "bert-base-cased"
layer_index: 7
dimension: 768
paths:
  train: "data_staging/embeddings/embeddings_ptb_sd/bert-base-cased_train_layers-all_align-mean.hdf5"
  dev: "data_staging/embeddings/embeddings_ptb_sd/bert-base-cased_dev_layers-all_align-mean.hdf5"
  test: "data_staging/embeddings/embeddings_ptb_sd/bert-base-cased_test_layers-all_align-mean.hdf5"